# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e8c91b3c8af2e3917da79d125334eec790a2fc04cc767d5dd176f37adc063b2d764a79e804c821cb1939bd9a6b1617350e9d3ea0607b63236eebb1eb01ac042

test:
  secret_key_base: fad554c71ee37e5b00e1fe1fc52554b11859fec27548dea802e9f8f31bd37b96dce30f699f6f46bb3560a30281a66acaff53c64fb00ef309c8f8c415f9adee96

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
